name: publish-dockerhub

on:
  push:
    branches: [master]
jobs:
  # This workflow contains a single job called "deploy_on_heroku"
  publish-dockerhub:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Set env
        run: echo "RELEASE_VERSION=latest" >> $GITHUB_ENV
# Set up JDK 13
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      # Builds Maven Proyect
      - name: Maven Package without test
        run: mvn -B clean package -DskipTests
# Next jobs creates a docker and pushes it to DockerHub

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.dockerhub_username}}
          password: ${{secrets.dockerhub_password}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_PROYECT}}:${{ env.RELEASE_VERSION }}
